import turtle
screen=turtle.Screen()
screen.screensize(500,500)
screen.bgcolor("aquamarine")
t=turtle.Turtle()
t2=turtle.Turtle()
t3=turtle.Turtle()
t.hideturtle()
t2.hideturtle()
t3.hideturtle()
t.pencolor('black')





#Intro Slide
t.penup()
t.goto(200,200)
t.pendown()
t.circle(20)
t.penup()
t.goto(0,150)
t.pendown()
t.write("All About Me",font=("Arial",30,"bold"),align="center")
t.penup()
t.goto(0,-150)
t.write("By: Christian Jones",font=("Arial",30,"bold"),align="center")
t.penup()
t.goto(-100,0)
t.pendown()
screen.addshape('me(1).gif')
t.shape('me(1).gif')
t.stamp()
t.shape("classic")
t.penup()
t.goto(100,0)
t.pendown()
screen.addshape('group(1).gif')
t.shape('group(1).gif')
t.stamp()
t.shape("classic")
t.penup()
t.goto(0,-250)
t.pendown()
t.write("Press Enter to Continue",font=("Arial",30,"bold"),align="center")
next = input("Press Enter to Continue: ")
t.penup()
t.clear()

#Slide 1
t.goto(-200,250)
t.pendown()
t.forward(30)
t.left(90)
t.forward(30)
t.left(90)
t.forward(30)
t.left(90)
t.forward(30)
t.left(90)
t.penup()
t.goto(0,200)
t.pendown()
t.write("My Favorite foods are:",font=("Arial",30,"bold"),align="center")
t.penup()
t.goto(-200,-100)
t.pendown()
t.write("Pizza",font=("Arial",30,"bold"),align="center")
t.penup()
t.goto(-200,0)
t.pendown()
screen.addshape('Pizza(1).gif')
t.shape('Pizza(1).gif')
t.stamp()
t.shape("classic")
t.penup()
t.goto(0,-100)
t.pendown()
t.write("&",font=("Arial",30,"bold"),align="center")
t.penup()
t.goto(200,-100)
t.pendown()
t.write("Sushi",font=("Arial",30,"bold"),align="center")
t.penup()
t.goto(200,0)
t.pendown()
screen.addshape('Sushi(1).gif')
t.shape('Sushi(1).gif')
t.stamp()
t.shape("classic")
t.penup()
t.goto(0,-200)
t.pendown()
t.write("Press Enter to Continue: ",font=("Arial",30,"bold"),align="center")
next = input("Press Enter to Continue: ")
t.clear()

#Slide 3
t.penup()
t.goto(-250,-250)
t.pendown()
t.setheading(45)
t.forward(50)
t.left(90)
t.forward(50)
t.left(90)
t.forward(50)
t.left(90)
t.forward(50)
t.left(90)
t.penup()
t.goto(0,200)
t.pendown()
t.write("My Hobbies are: ",font=("Arial",30,"bold"),align="center")
t.penup()
t.goto(-150,-100)
t.pendown()
t.write("Volleyball",font=("Arial",30,"bold"),align="center")
t.penup()
t.goto(-150,50)
t.pendown()
screen.addshape('Volleyball(1).gif')
t.shape('Volleyball(1).gif')
t.stamp()
t.shape("classic")
t.penup()
t.goto(0,-100)
t.pendown()
t.write("&",font=("Arial",30,"bold"),align="center")
t.penup()
t.goto(150,-100)
t.pendown()
t.write("Band",font=("Arial",30,"bold"),align="center")
t.penup()
t.goto(150,50)
t.pendown()
screen.addshape('Band(1).gif')
t.shape('Band(1).gif')
t.stamp()
t.shape("classic")
t.penup()
t.goto(0,-200)
t.write("Press Enter to Continue: ",font=("Arial",30,"bold"),align="center")
next = input("Press Enter to Continue: ")
t.clear()

#Slide 4
t.penup()
t.goto(250,-250)
t.pendown()
t.goto(275,-240)
t.goto(250,-230)
t.goto(225,-260)
t.goto(250,-250)
t.penup()
t.goto(0,200)
t.pendown()
t.write("My Favorite Movie is: ",font=("Arial",30,"bold"),align="center")
t.penup()
t.goto(0,-200)
t.pendown()
t.write("A Simple Favor",font=("Arial",30,"bold"),align="center")
t.penup()
t.goto(-125,0)
t.pendown()
screen.addshape('Movie(1).gif')
t.shape('Movie(1).gif')
t.stamp()
t.shape("classic")
t.penup()
t.goto(125,0)
t.pendown()
screen.addshape('Movie(2).gif')
t.shape('Movie(2).gif')
t.stamp()
t.shape("classic")
t.penup()
t.goto(0,-250)
t.pendown()
t.write("Press Enter to Continue: ",font=("Arial",30,"bold"),align="center")
next = input("Press Enter to Continue: ")
t.clear()

#Slide 5
t.penup()
t.goto(0,150)
t.pendown()
t.write("My Favorite Sport is: ",font=("Arial",30,"bold"),align="center")
t.penup()
t.goto(0,-150)
t.pendown()
t.write("Volleyball",font=("Arial",30,"bold"),align="center")
t.penup()
t.goto(-100,0)
t.pendown()
screen.addshape('Volleyball(2).gif')
t.shape('Volleyball(2).gif')
t.stamp()
t.shape("classic")
t.penup()
t.goto(100,0)
t.pendown()
screen.addshape('Volleyball(3).gif')
t.shape('Volleyball(3).gif')
t.stamp()
t.shape("classic")
t.penup()
t.goto(0,-250)
t.pendown()
t.setheading(0)
t.right(90)
t.forward(20)
t.right(90)
t.forward(50)
t.right(90)
t.forward(20)
t.goto(0,-250)
t.penup()
t.goto(0,-200)
t.write("Press Enter to Continue: ",font=("Arial",30,"bold"),align="center")
next = input("Press Enter to Continue: ")
t.clear()

#End Slide
t.penup()
t.goto(0,200)
t.pendown()
t.write("The End",font=("Arial",30,"bold"),align="center")
t.penup()
t.goto(0,0)
t.pendown()

#No code after this
turtle.done()